// UUIDv7 generation in application code (LLD §0.2, RFC 9562).
import type { Id } from './types.js';

let lastMs = -1;
let lastSeq = 0;

function randomBytes(n: number): Uint8Array {
  const b = new Uint8Array(n);
  globalThis.crypto.getRandomValues(b);
  return b;
}

/**
 * Returns a UUIDv7 string. Within the same millisecond a 12-bit counter in
 * `rand_a` keeps ids generated by this process monotonic.
 */
export function uuidv7(nowMs: number = Date.now()): string {
  let ms = Math.floor(nowMs);
  if (ms <= lastMs) {
    ms = lastMs;
    lastSeq += 1;
    if (lastSeq > 0xfff) {
      // Counter overflow: borrow the next millisecond.
      ms = lastMs + 1;
      lastSeq = randomBytes(1)[0]! & 0x7f;
    }
  } else {
    lastSeq = randomBytes(1)[0]! & 0x7f; // leave headroom for increments
  }
  lastMs = ms;

  const bytes = randomBytes(16);
  // 48-bit big-endian timestamp.
  let t = ms;
  for (let i = 5; i >= 0; i--) {
    bytes[i] = t % 256;
    t = Math.floor(t / 256);
  }
  bytes[6] = 0x70 | ((lastSeq >> 8) & 0x0f); // version 7
  bytes[7] = lastSeq & 0xff;
  bytes[8] = 0x80 | (bytes[8]! & 0x3f); // variant 10

  const hex = Array.from(bytes, (x) => x.toString(16).padStart(2, '0')).join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

export function newId<T extends string>(): Id<T> {
  return uuidv7() as Id<T>;
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isUuid(s: unknown): s is string {
  return typeof s === 'string' && UUID_RE.test(s);
}
