"""M08 Source licence register and connector framework — Python public API (IF-08a/b).

REQ-036; enabling REQ-033 (source attribution) and REQ-048 (export rights).
Other knowledge-plane modules import only from here.
"""
from .connector import (
    BUDGET_CHECK_EVERY,
    Connector,
    FetchRequest,
    RawItem,
    RawRef,
    Record,
    RecordSink,
    RunStats,
    SourceStorageForbidden,
)
from .http import (
    HttpResponse,
    ProhibitedHost,
    RobotsDisallowed,
    http_fetch,
    robots_allows,
    set_transport_for_testing,
    user_agent,
)
from .lifecycle import (
    SYNC_LIFECYCLE_JOB,
    build_lifecycle_rules,
    register_drift,
    register_source_jobs,
    sync_raw_lifecycle,
)
from .register import (
    ALL_REGIONS,
    PROHIBITED_HOSTS,
    PROHIBITED_SOURCE_IDS,
    SourceEntry,
    SourceNotActive,
    SourceNotRegistered,
    clear_source_cache,
    get_source,
    is_prohibited_host,
    load_register_file,
    lookup_source,
    register_entries_loader,
    set_source_loader_for_testing,
    validate_entry,
)
from .storage import (
    DbRawIndex,
    MemoryRawIndex,
    MemoryRawStore,
    RawIndex,
    RawObjectRow,
    RawStore,
    S3RawStore,
    raw_bucket_name,
    raw_key,
)

__all__ = [
    "ALL_REGIONS",
    "BUDGET_CHECK_EVERY",
    "PROHIBITED_HOSTS",
    "PROHIBITED_SOURCE_IDS",
    "SYNC_LIFECYCLE_JOB",
    "Connector",
    "DbRawIndex",
    "FetchRequest",
    "HttpResponse",
    "MemoryRawIndex",
    "MemoryRawStore",
    "ProhibitedHost",
    "RawIndex",
    "RawItem",
    "RawObjectRow",
    "RawRef",
    "RawStore",
    "Record",
    "RecordSink",
    "RobotsDisallowed",
    "RunStats",
    "S3RawStore",
    "SourceEntry",
    "SourceNotActive",
    "SourceNotRegistered",
    "SourceStorageForbidden",
    "build_lifecycle_rules",
    "clear_source_cache",
    "get_source",
    "http_fetch",
    "is_prohibited_host",
    "load_register_file",
    "lookup_source",
    "raw_bucket_name",
    "raw_key",
    "register_drift",
    "register_entries_loader",
    "register_source_jobs",
    "robots_allows",
    "set_source_loader_for_testing",
    "set_transport_for_testing",
    "sync_raw_lifecycle",
    "user_agent",
    "validate_entry",
]
