"""M03 LLM adapter — Python public API (IF-03a mirror). Other modules import only from here."""
from .adapter import (
    CACHE_PREFIX,
    LLM_BAD_OUTPUT,
    LlmBadOutputError,
    LlmRequest,
    LlmResult,
    LlmStream,
    complete,
    cost_op,
    embed,
    llm_cache_key,
    set_llm_cache_client_for_testing,
    stream,
)
from .config import (
    LlmConfig,
    ModelTarget,
    TierConfig,
    build_llm_config,
    cost_micros_inr,
    get_llm_config,
    load_llm_config,
    set_llm_config_for_testing,
)
from .guard import assert_no_pii, detect_pii, extract_json, parse_and_validate, validate_json
from .providers import (
    ProviderCall,
    ProviderCompletion,
    ProviderEmbedding,
    ProviderHttpError,
    ProviderTimeout,
    StreamEvent,
    get_llm_provider,
    register_llm_provider,
    unregister_llm_provider,
)

__all__ = [
    "CACHE_PREFIX",
    "LLM_BAD_OUTPUT",
    "LlmBadOutputError",
    "LlmConfig",
    "LlmRequest",
    "LlmResult",
    "LlmStream",
    "ModelTarget",
    "ProviderCall",
    "ProviderCompletion",
    "ProviderEmbedding",
    "ProviderHttpError",
    "ProviderTimeout",
    "StreamEvent",
    "TierConfig",
    "assert_no_pii",
    "build_llm_config",
    "complete",
    "cost_micros_inr",
    "cost_op",
    "detect_pii",
    "embed",
    "extract_json",
    "get_llm_config",
    "get_llm_provider",
    "llm_cache_key",
    "load_llm_config",
    "parse_and_validate",
    "register_llm_provider",
    "set_llm_cache_client_for_testing",
    "set_llm_config_for_testing",
    "stream",
    "unregister_llm_provider",
    "validate_json",
]
